name: Build OnePlus 9 Pro Kernel

on:
  workflow_dispatch:

env:
  KERNEL_REPO: smualemi/android_kernel_oneplus_sm8350
  KERNEL_BRANCH: oneplus/sm8350_u_14.0.0_oneplus9
  DEVICE_TREE_REPO: smualemi/android_kernel_modules_and_devicetree_oneplus_sm8350
  DEVICE_TREE_BRANCH: oneplus/sm8350_u_14.0.0_oneplus9

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 180

    steps:

# ------------------------------------------------
# Checkout Sources
# ------------------------------------------------

    - uses: actions/checkout@v4

    - name: Kernel Source
      uses: actions/checkout@v4
      with:
        repository: ${{ env.KERNEL_REPO }}
        ref: ${{ env.KERNEL_BRANCH }}
        path: kernel/msm-5.4

    - name: Device Tree
      uses: actions/checkout@v4
      with:
        repository: ${{ env.DEVICE_TREE_REPO }}
        ref: ${{ env.DEVICE_TREE_BRANCH }}
        path: devicetree

# ------------------------------------------------
# Dependencies
# ------------------------------------------------

    - name: Install packages
      run: |
        sudo apt update
        sudo apt install -y \
        bc bison build-essential flex git \
        libssl-dev libelf-dev lzop \
        python3 cpio zip unzip rsync

# ------------------------------------------------
# Toolchain
# ------------------------------------------------

    - name: Clone Clang
      run: |
        git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 \
        -b android11-release --depth=1 clang

# ------------------------------------------------
# Prepare AOSP layout
# ------------------------------------------------

    - name: Setup workspace
      run: |

        mkdir device
        mkdir vendor

        rsync -a devicetree/device/ device/
        rsync -a devicetree/vendor/ vendor/

# ------------------------------------------------
# Build Kernel
# ------------------------------------------------

    - name: Build kernel
      run: |

        export PATH=$GITHUB_WORKSPACE/clang/clang-r383902b/bin:$PATH

        export CC=clang
        export LLVM=1
        export LLVM_IAS=1

        export KERNEL_DIR=kernel/msm-5.4

        cd $GITHUB_WORKSPACE

        bash device/qcom/kernelscripts/build.sh

# ------------------------------------------------
# Collect kernel
# ------------------------------------------------

    - name: Get kernel image
      run: |

        echo "Searching kernel..."

        find out -name Image

        cp out/msm-5.4-lahaina-qgki*/dist/Image kernel

# ------------------------------------------------
# Upload
# ------------------------------------------------

    - uses: actions/upload-artifact@v4
      with:
        name: kernel-image
        path: kernel/Image
